"""Add indexes

Revision ID: 51cfc6a7c67c
Revises: 56cc1d5555b8
Create Date: 2025-02-23 10:07:05.557542

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "51cfc6a7c67c"
down_revision: str | None = "56cc1d5555b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_messages_chat_created", "messages", ["chat_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_chat_created", table_name="messages")
    # ### end Alembic commands ###
