"""Add cascade delete to foreign keys

Revision ID: 5c69d2330eaf
Revises: dff01af2f411
Create Date: 2025-02-22 13:01:51.855471

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5c69d2330eaf"
down_revision: str | None = "dff01af2f411"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chat_members_user_id_fkey", "chat_members", type_="foreignkey")
    op.drop_constraint("chat_members_chat_id_fkey", "chat_members", type_="foreignkey")
    op.create_foreign_key(
        None, "chat_members", "chats", ["chat_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "chat_members", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("chats_group_id_fkey", "chats", type_="foreignkey")
    op.create_foreign_key(
        None, "chats", "groups", ["group_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "group_members_group_id_fkey", "group_members", type_="foreignkey"
    )
    op.drop_constraint(
        "group_members_user_id_fkey", "group_members", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "group_members", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "group_members", "groups", ["group_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("groups_creator_id_fkey", "groups", type_="foreignkey")
    op.create_foreign_key(
        None, "groups", "users", ["creator_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("messages_sender_id_fkey", "messages", type_="foreignkey")
    op.drop_constraint("messages_chat_id_fkey", "messages", type_="foreignkey")
    op.create_foreign_key(
        None, "messages", "chats", ["chat_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "messages", "users", ["sender_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(
        "messages_chat_id_fkey", "messages", "chats", ["chat_id"], ["id"]
    )
    op.create_foreign_key(
        "messages_sender_id_fkey", "messages", "users", ["sender_id"], ["id"]
    )
    op.drop_constraint(None, "groups", type_="foreignkey")
    op.create_foreign_key(
        "groups_creator_id_fkey", "groups", "users", ["creator_id"], ["id"]
    )
    op.drop_constraint(None, "group_members", type_="foreignkey")
    op.drop_constraint(None, "group_members", type_="foreignkey")
    op.create_foreign_key(
        "group_members_user_id_fkey", "group_members", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "group_members_group_id_fkey", "group_members", "groups", ["group_id"], ["id"]
    )
    op.drop_constraint(None, "chats", type_="foreignkey")
    op.create_foreign_key(
        "chats_group_id_fkey", "chats", "groups", ["group_id"], ["id"]
    )
    op.drop_constraint(None, "chat_members", type_="foreignkey")
    op.drop_constraint(None, "chat_members", type_="foreignkey")
    op.create_foreign_key(
        "chat_members_chat_id_fkey", "chat_members", "chats", ["chat_id"], ["id"]
    )
    op.create_foreign_key(
        "chat_members_user_id_fkey", "chat_members", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
