"""Update ChatMember model

Revision ID: a86386916029
Revises: 51cfc6a7c67c
Create Date: 2025-02-23 10:09:13.661771

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a86386916029"
down_revision: str | None = "51cfc6a7c67c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chat_members_unique", "chat_members", type_="unique")
    op.drop_column("chat_members", "id")
    op.drop_column("chat_members", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_members",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "chat_members", sa.Column("id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.create_unique_constraint(
        "chat_members_unique", "chat_members", ["chat_id", "user_id"]
    )
    # ### end Alembic commands ###
