"""Add idempotency key to Message table

Revision ID: eb04f64df5b3
Revises: 3a14a17dbc54
Create Date: 2025-02-25 21:35:16.857023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb04f64df5b3'
down_revision: Union[str, None] = '3a14a17dbc54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sender_idempotency_key', 'messages', ['sender_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sender_idempotency_key', 'messages', type_='unique')
    # ### end Alembic commands ###
